version: '3.5'

services:
    batch:
        build:
            dockerfile: Dockerfile.dev
            context: .
        container_name: blackblade-batch
        environment:
            - BASE_SCRYFALL_URL=https://api.scryfall.com
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - DB_DATABASE=blackblade
            - DB_HOST=blackblade-db
            - DB_PORT=3306

networks:
    default:
        external:
            name: blackblade_core
