version: 2.1

orbs:
    digitalocean: digitalocean/cli@0.1.1
    kubernetes: digitalocean/k8s@0.1.1

workflows:
    production:
        jobs:
            - build:
                  context:
                      - blackblade
                  filters:
                      branches:
                          only:
                              - master
            - approve:
                  requires:
                      - build
                  type: approval
                  filters:
                      branches:
                          only:
                              - master
            - deploy:
                  requires:
                      - approve
                  context:
                      - blackblade
                  filters:
                      branches:
                          only:
                              - master
jobs:
    build:
        machine: true
        steps:
            - checkout
            - run:
                  name: 'Build & push images to Dockerhub'
                  command: |
                      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                      docker build -t brandonwade/blackblade-batch:latest -t brandonwade/blackblade-batch:$CIRCLE_SHA1 -f ./Dockerfile .
                      docker push brandonwade/blackblade-batch:latest
                      docker push brandonwade/blackblade-batch:$CIRCLE_SHA1
    deploy:
        executor: digitalocean/default
        steps:
            - checkout
            - kubernetes/install
            - kubernetes/initialize:
                  cluster: $DO_CLUSTER_NAME
            - run:
                  name: 'Set up Digital Ocean cluster configs'
                  command: |
                      doctl kubernetes cluster kubeconfig save $DO_CLUSTER_ID
            - run:
                  name: 'Update Kubernetes with the latest configs'
                  command: |
                      kubectl apply -f ./k8s
            - run:
                  name: 'Update pods with the latest image versions'
                  command: |
                      kubectl set image cronjobs/batch-cronjob blackblade-batch=brandonwade/blackblade-batch:$CIRCLE_SHA1
