version: 2.1

jobs:
    build_and_deploy:
        docker:
            - image: google/cloud-sdk
        steps:
            - checkout
            - setup_remote_docker
            - run:
                  name: 'Build & push images to Dockerhub'
                  command: |
                      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                      docker build -t brandonwade/blackblade-batch:latest -t brandonwade/blackblade-batch:$CIRCLE_SHA1 -f ./Dockerfile .
                      docker push brandonwade/blackblade-batch:latest
                      docker push brandonwade/blackblade-batch:$CIRCLE_SHA1
            # - run:
            #       name: 'Authenticate with GCP'
            #       command: |
            #           openssl aes-256-cbc -d -in service-account.json.enc -out service-account.json -k $SERVICE_ACCOUNT_ENCRYPTION_KEY -md sha256
            #           gcloud auth activate-service-account --key-file=service-account.json
            #           gcloud --quiet config set project ${GCP_PROJECT_ID}
            #           gcloud --quiet config set compute/zone ${GCP_COMPUTE_ZONE}
            #           gcloud container clusters get-credentials ${GCP_CLUSTER_NAME}
            # - run:
            #       name: 'Update Kubernetes with the latest configs'
            #       command: |
            #           kubectl apply -f k8s
            # - run:
            #       name: 'Update pods with the latest image versions'
            #       command: |
            #           kubectl set image deployments/batch-deployment blackblade-batch=brandonwade/blackblade-batch:$CIRCLE_SHA1
workflows:
    version: 2.1
    build_and_deploy:
        jobs:
            - build_and_deploy:
                  filters:
                      branches:
                          only:
                              - master
