apiVersion: batch/v1
kind: CronJob
metadata:
    name: batch-cronjob
spec:
    schedule: '0 0 * * 6'
    successfulJobsHistoryLimit: 0
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                        - name: blackblade-batch
                          image: brandonwade/blackblade-batch:latest
                          env:
                              - name: BASE_SCRYFALL_URL
                                value: https://api.scryfall.com
                              - name: DB_USERNAME
                                valueFrom:
                                    secretKeyRef:
                                        name: mysqluser
                                        key: MYSQL_USER
                              - name: DB_PASSWORD
                                valueFrom:
                                    secretKeyRef:
                                        name: mysqlpassword
                                        key: MYSQL_PASSWORD
                              - name: DB_DATABASE
                                value: blackblade
                              - name: DB_HOST
                                valueFrom:
                                    secretKeyRef:
                                        name: dbhost
                                        key: DB_HOST
                              - name: DB_PORT
                                valueFrom:
                                    secretKeyRef:
                                        name: dbport
                                        key: DB_PORT
                    restartPolicy: OnFailure
