apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: batch-cronjob
spec:
    schedule: '35 * * * *'
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                        - name: blackblade-batch
                          image: brandonwade/blackblade-batch:latest
                          env:
                              - name: BASE_SCRYFALL_URL
                                value: https://api.scryfall.com
                              - name: DB_USERNAME
                                value: blackblade
                              - name: DB_PASSWORD
                                valueFrom:
                                    secretKeyRef:
                                        name: mysqlpassword
                                        key: MYSQL_PASSWORD
                              - name: DB_DATABASE
                                value: blackblade
                              - name: DB_HOST
                                value: db-cluster-ip-service
                              - name: DB_PORT
                                value: '3306'
                    restartPolicy: OnFailure
                    imagePullSecrets:
                        - name: regcred
